<?php

namespace SimpleFramework;

use Valitron\Validator;

abstract class Model extends \Illuminate\Database\Eloquent\Model
{
    protected  $fillable = [];
    public  $attributes = [];
    protected $loaded = [];
    protected string $name_lang = 'ru';

    protected array $rules = [];
    protected array $errors =[];

    protected array $labels = [];

    public function loadData():void
    {
        $data = request()->getData();

        foreach($this->loaded as $load){
            if(isset($data[$load]))
            {
                $this->attributes[$load] = $data[$load];
            }else{
                $this->attributes[$load] = '';
            }
        }
    }

    public function save(array $options = [])
    {
        foreach($this->attributes as $name => $value){
            if(!in_array($name, $this->fillable)){
                unset($this->attributes[$name]);
            }
        }
        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function validate($data = '', $rules = '', $labels = '', $name_lang = ''):bool
    {
        if(!$data){
            $data = $this->attributes;
        }
        if(!$rules)
        {
            $rules = $this->rules;
        }
        if(!$name_lang)
        {
            $name_lang = $this->name_lang;
        }
        if(!$labels)
        {
            $labels = $this->labels;
        }

        Validator::langDir(WWW."/lang");
        Validator::lang($name_lang);

        $validator = new Validator($data);
        $validator->rules($rules);
        $validator->labels($labels);
        if($validator->validate()){
            return true;
        }else{
            $this->errors = $validator->errors();
            return false;
        }
    }

    public function getErrors():array
    {
        return $this->errors;
    }
}